### ISSUE TITLE
Unable to Download .exe file from vlabs landing pages for some experiments

### ISSUE THREAD

**Issue by madhavipuliraju** [openedx-vlead/open-edx-medical-signal-and-image-processing-lab-iitr#1]
Unable to Download .exe file from vlabs landing pages for the following experiments:
1) Digital Signal Processing Toolkit 
2) Bio-Medical Signal Processing Toolkit

**Comment by sanchita-dixit** [comment]
I am able to download the exe files for the above mentioned experiments. Assigning this issue to @ksripathi for further resolution

**Comment by mrudhvika940** [comment]
**target** was not mentioned so, it was unable to download

`<a href=url **target="[object Object]"**>text </a>`

 After making above changes to the experiment script the lab is working fine

**Comment by sravanthimodepu** [comment]
When we click on download link, it is redirecting to the google drive download page instead of a popup to download the ".exe" file directly.
![med](https://user-images.githubusercontent.com/11156924/35903258-6192d2d0-0c04-11e8-8317-e22ba318d626.png)

**Comment by sravanthimodepu** [comment]
Closing the issue, as the simulations are downloadable.
